# Generated by Django 2.2 on 2020-02-18 14:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bf', tinymce.models.HTMLField(blank=True, default='')),
            ],
        ),
    ]
