# Generated by Django 2.2 on 2020-02-26 11:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tinymce.models.HTMLField(blank=True, default='')),
                ('bk', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mytest.book')),
            ],
        ),
    ]
