# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='无标题')),
                ('content', models.TextField(blank=True, default='这个人很懒，没有写任何内容...')),
                ('subTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
