# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contest', '0001_initial'),
        ('Issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsubmit',
            name='problem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Issue.Problem'),
        ),
    ]
